// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtvZvwhSn4rmBBl6OLNCq5Y9yClZJe6QA',
    appId: '1:1013512034521:web:739243dd4ad956704046c8',
    messagingSenderId: '1013512034521',
    projectId: 'uthmsync5',
    authDomain: 'uthmsync5.firebaseapp.com',
    storageBucket: 'uthmsync5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNCkBDMCXejaJJrayDfyB_iJog9sDzpck',
    appId: '1:1013512034521:android:d58268a134132cb64046c8',
    messagingSenderId: '1013512034521',
    projectId: 'uthmsync5',
    storageBucket: 'uthmsync5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Ox7DUjKWlR6v207yXgXlvarqAkRs7Zg',
    appId: '1:1013512034521:ios:b7f76d9901e527454046c8',
    messagingSenderId: '1013512034521',
    projectId: 'uthmsync5',
    storageBucket: 'uthmsync5.appspot.com',
    iosBundleId: 'com.example.uthmsync5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Ox7DUjKWlR6v207yXgXlvarqAkRs7Zg',
    appId: '1:1013512034521:ios:0a3f7f2943df2a714046c8',
    messagingSenderId: '1013512034521',
    projectId: 'uthmsync5',
    storageBucket: 'uthmsync5.appspot.com',
    iosBundleId: 'com.example.uthmsync5.RunnerTests',
  );
}
